### ISSUE TITLE
SOW: Email Notifications

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#442]
## Summary
[SOW](https://docs.google.com/document/d/1YthZ9Jhh5Tfmap73BgpN5IAmcVk95aSHbNNludpVXYg/edit)

The goal is to implement email notifications for some activities/trigers in the Hyku application. That include:
- Notifications to submitter and approver for activity related to mediated deposit, which currently produce notifications within the app but not pushed out to email.  These including:
  - Work submitted awaiting review
  - Work reviewed and accepted
  - Work reviewed and sent back with comment
  - Work revised and resubmitted for review
- Notifications to authors related to views and downloads of their works.

SoftServ will hook into the workflow callbacks to trigger notifications and set up notifications to trigger emails.  The primary goal of this work is the implementation of email notifications related to mediated deposit.  In SoftServ’s preliminary assessment the work to trigger email notifications for other activities and expand this requirement to meet the request from PALNI and PALCI to provide email notifications for views and downloads would not have a significant affect on scope and should be accomplishable within these sprints. 

SoftServ allocates one 1-week sprint (apprx. 90 hours) including two senior engineers, project management, and QA resources to accomplish these goals.

[See the below "Implementation Way Finding" for guidance on the submitter activity](https://github.com/scientist-softserv/palni-palci/issues/1005#issuecomment-2052160513)

## TASKS
- [ ] notch8/palni_palci_knapsack#435
  - [x] https://github.com/scientist-softserv/palni-palci/issues/1022
  - [x] https://github.com/scientist-softserv/palni-palci/issues/1023
- [ ] notch8/palni_palci_knapsack#434

## Acceptance Criteria
- [ ] Email notifications to submitter and approver for activity related to mediated deposit are set up and include: ([see below](https://github.com/scientist-softserv/palni-palci/issues/1005#issuecomment-2052160513))
  - [ ] Work submitted awaiting review
  - [ ] Work reviewed and accepted
  - [ ] Work reviewed and sent back with comment
  - [ ] Work revised and resubmitted for review
- [ ] Email notifications to authors related to views and downloads of their works are set up
  - (Jeremy here: the notifications of this bullet point are not handled in the "Implementation Way Finding" and require a different approach.)

## Note
This work is not perfectly defined at the time of the SOW.  The scope of the email notifications around author/work activity has the risk of ballooning.  The spirit of this from Pitt was:  We need email notifications for mediated deposit, and would like to include Pals' requirements if possible.  Before we finalize this work, we should define options with Pitt, share scope concerns, estimate what is manageable within this sprint, and have Pitt/Pals prioritize accordingly armed with that knowledge.
  
Similar work was done for DOT: https://assaydepot.slack.com/archives/C0311DNF3MG/p1713215197011169

May be helpful: https://samvera.github.io/email_notifications.html or https://github.com/samvera/hyrax/wiki/Notifications-and-Messages

MAIL DEV setup: https://playbook-staging.notch8.com/en/devops/maildev
